Version v1.01 released.

diff --git a/gittools/vfpgitdiff b/gittools/vfpgitdiff
--- a/gittools/vfpgitdiff
+++ b/gittools/vfpgitdiff
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 ###############################################################################
-# VFPGitDiff v1.0, by Ignacio Serantes                                        #
+# VFPGitDiff v1.01, by Ignacio Serantes                                       #
 ###############################################################################
 # Usage:                                                                      #
 #   vfpgitdiff <filename> [ commit_id_from [ commit_id_to ] ]                 #
@@ -12,26 +12,28 @@
 #   commit_id_to    - optional, by default local file is used                 #
 #                                                                             #
 # Remarks:                                                                    #
-#   - WinMerge is required and configured in WINMERGE constant.               #
-#   - FoxBin2Prg is required and configured in FOXBIN2PRG constant.           #
+#   - WinMerge is required and configured in BIN_WINMERGE constant.           #
+#   - FoxBin2Prg is required and configured in BIN_FOXBIN2PRG constant.       #
 #   - Changes made in WinMerge's right panel will update local files.         #
-#     Disable this feature with UPDATEONCHANGE=0.                             #
+#     This feature can be disabled setting UPDATEONCHANGE=0.                  #
 #                                                                             #
 ###############################################################################
 # History:                                                                    #
-#   2020-02-09 - First version v1.0                                           #
+#   2020-03-10 - v1.01, Minor changes in constants, help and documentation.   #
+#   2020-02-09 - v1.00, First version.                                        #
 #                                                                             #
 ###############################################################################
 
 #
 # Script configuration.
 #
-PRGNAME="VFGGitDiff"
-PRGAUTHOR="Ignacio Serantes"
-PRGVERSION="1"
-PRGSUBVERSION="0"
-WINMERGE="/c/Program Files/WinMerge/WinMergeU.exe"
-FOXBIN2PRG="/c/Users/ignacio/Apps/vfpx/foxbin2prg/foxbin2prg.exe"
+PRG_NAME="VFGGitDiff"
+PRG_AUTHOR="Ignacio Serantes"
+PRG_VERSION="1"
+PRG_RELEASE="01"
+BIN_WINMERGE="/c/Program Files/WinMerge/WinMergeU.exe"
+BIN_FOXBIN2PRG="/c/Users/ignacio/Apps/vfpx/foxbin2prg/foxbin2prg.exe"
+
 FOXBIN2PRGSUFFIX='2'
 #FOXBIN2PRGSUFFIX='a'
 UPDATEONCHANGE=1
@@ -44,14 +46,13 @@ UPDATEONCHANGE=1
 
 # No parameters then help.
 if [ -z "$1" ]; then
-    echo $0
-    echo "$PRGNAME v$PRGVERSION.$PRGSUBVERSION by $PRGAUTHOR
+    echo "$PRG_NAME v$PRG_VERSION.$PRG_RELEASE by $PRG_AUTHOR
     
 Usage:
     $(basename "$(test -L "$0" && readlink "$0" || echo "$0")") <filename> [ commit_id_from [ commit_id_to ] ]
     
 Options:
-    filename        - required,  working file name
+    filename        - required, working file name
     commit_id_from  - optional, by default last commit id is used
     commit_id_to    - optional, by default local file is used
     
@@ -120,14 +121,14 @@ function CfgCheck {
     fi
     
     # WinMerge.
-    if ! [ -f "$WINMERGE" ]; then
-        echo "ERROR: WINMERGE constant is incorrectly configured."
+    if ! [ -f "$BIN_WINMERGE" ]; then
+        echo "ERROR: BIN_WINMERGE constant is incorrectly configured."
         exit -1
     fi
     
     # FoxBin2Prg.
-    if ! [ -f "$FOXBIN2PRG" ]; then
-        echo "ERROR: FOXBIN2PRG constant is incorrectly configured."
+    if ! [ -f "$BIN_FOXBIN2PRG" ]; then
+        echo "ERROR: BIN_FOXBIN2PRG constant is incorrectly configured."
         exit -1
     fi
 
@@ -396,17 +397,17 @@ if ! [ -z "$EXTAUX" ]; then
         exit -1
     fi
     
-    "$FOXBIN2PRG" BIN2PRG "$FILEFROM"
-    "$FOXBIN2PRG" BIN2PRG "$FILETO"
+    "$BIN_FOXBIN2PRG" BIN2PRG "$FILEFROM"
+    "$BIN_FOXBIN2PRG" BIN2PRG "$FILETO"
     
     LTIME=$(stat -c %Z "${FILETO%.*}.$EXTFOXBIN2PRG")
-    "$WINMERGE"  "${FILEFROM%.*}.$EXTFOXBIN2PRG" "${FILETO%.*}.$EXTFOXBIN2PRG"
+    "$BIN_WINMERGE"  "${FILEFROM%.*}.$EXTFOXBIN2PRG" "${FILETO%.*}.$EXTFOXBIN2PRG"
     ATIME=$(stat -c %Z "${FILETO%.*}.$EXTFOXBIN2PRG")
 
 else
 
     LTIME=$(stat -c %Z "$FILETO")
-    "$WINMERGE" "$FILEFROM" "$FILETO"
+    "$BIN_WINMERGE" "$FILEFROM" "$FILETO"
     ATIME=$(stat -c %Z "$FILETO")
 
 fi
@@ -417,7 +418,7 @@ if [ $UPDATEONCHANGE -eq 1 ] && [[ "$ATIME" != "$LTIME" ]]; then
     # Handle Visual FoxPro binary elements with two files (classlib, forms, etc...).
     if ! [ -z "$EXTAUX" ]; then
 
-        "$FOXBIN2PRG" PRG2BIN "${FILETO%.*}.$EXTFOXBIN2PRG"
+        "$BIN_FOXBIN2PRG" PRG2BIN "${FILETO%.*}.$EXTFOXBIN2PRG"
 
         FILENAMEAUX="$(GetRealFileName "$PWD" "$FILEREALDIR" "$FILESTEM.$EXTAUX")"
         if [ $? -ne 0 ]; then
